language: node_js
node_js:
- '6'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
- cp config/localSettings.js.in config/localSettings.js
script:
- yarn install --ignore-engines
- npm test
- npm run test:integration
notifications:
  - slack:
    secure: sZMduFi62gZofudI39qlGce0l2lg5inlHlUHZ9cw3WiB1gyzYbtaxq2yqjOgs/aKpoCwqjgkBIFt3aCQrTFQ5eeXmsrldFzpzEUguetOwoM+iZqiziqOFdcav2ImxrbX9cCJmsf9PrM19JO+IEXajlHEOaT492TGuQiXYCSTq8nPA25DJ50a8lQuN/r/fa+k+SCpZuXOlYw2GAI+Bm2NP8ALcUy+q9/HhG++80e47fELDz3bYqyxNopDjhylbszplbTCmxkpYK1pARVgaiFgWE0J34aevEplm8taYvdUwq7VmphsZsoIHZT0scbZxcMALhXofQBhFG5qAB7cZz8i6EjiLKzE7u5/GoPcj7IXgaW9dqcpVDxGYM6nlxR0IkAO9YVoMoOHToxB0vp3LXACVKgrIzJWBQVHWZWbDEeNex4bPC6NJFrOwEjyzxa3yf7mThrPfXujB6F37aoNXw37/v2v14bBsVugLsEVNE+yWm9HXItOA8tZ0RMd8XTZOyC8xIMgt88At52lkJYB193rg+GM7dzEDm5v2PJLrEwepWcImNxyXm2ByZ/XhBZiY8YfwDFkU97ez/plEs08uZqaAKVj0IZkNNHO7RQ6m1CyV4Ej1UK7fZIXxQSJlRDG1vSWrSxDQpwE6BafZzQeX+7GD4U2JQsgtCiajOD9ms4OpTM=
  - slack:
    secure: M6o42yyVQsBmXKlfWZBb8omoHYqovA7+ShSsrZACyW2bBORXBrhOL6lFVdc7U7i6IAdyOUwNHQAsAuYI9S6ECOhVyHedkmlH+QFi0bLutjSa3Jx648TkSzu5z5180WbyWm44R8bstS8/BGSljvoypWijePsxrYm0hHyjMDo2kxHwLtYZyK1KJBr+EQ7CpyORAq+T2EN+GzHi8cwTCjoAihT1TaEYWo81YqtsRwLFpCPxYT18Ctz6O89Rf5ydM49KORf0Tfdj+2Vq1LeORdMQ5MkvhhRkhG9sSxJuY/j90hWutGnHPUOfI310bCxf4Q1g0Boq+U2o7pgd3a3vmCRvRQbcprdfjZ0TH1vKIqltYMnMz8+eaSp/KpLdHTFknzjdxx24CRPZ2qPhA5HTheeQAPokdDw/x4nxkrhXQxny6Efbhbx+CZrVOabsI9cO4QQDqb4aQ7HBLrI3syRYW9WJGsKR+u3c7NB2W21uBbB01swva3ozlXto1NWQ/1krXwNMSW8sMHmby5b/CaSMgZAtdFSafDLcRXkUWl0YdDLMiqVf7yepgCa0tEscIQ05VdqKhpXK8v032a12Veliwdknq5RQ0oWIGaIye32C2POJSPQ+xWkFD6X5wD6ig/St9yD630XQcAG0gB59CdGZ/ywC1Urw3QD0x9zXJxmEr1B5+xc=
