language: node_js
node_js:
- '6'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
- cp config/localSettings.js.in config/localSettings.js
script:
- yarn install --ignore-engines
- npm test
- npm run test:integration
notifications:
  on_success: change
  on_failure: always
  slack:
    secure: o8JMnWvzmuqlRAcbRs/Hnv/aOX1743tTrpanSmGEIYJwT9eJm8TG7dyckKQqUmo6qKBU7ANc1uXP5kusDgzQDsZOQGolIhFEGJTNbTHdzVe+pp9wIWyLhn2ptZlaaiKRkkcMJAvRNWoa3dOvPWT3NxGkDMHboEm72vXt7jcPwpgNzhY6FK+6WqZnXTh5RTlSHlm+rkYqZG1DHuOf+1tc9CpJbQAFa3KRSSpToNGgkN9TcxnwZyYWSafRWIa0nSNly3ZnLDafppXOem9xZ45VS/bTey2n47oVW6bzWTJHxEbT04Hg2ZqxMRjXZNmAtvGkscc4NBxBGkdHmKLbQpavLlOSG6iOLexYh8j85v+MLIfw+RPOG8X7Ju1zHjFxxlGRCcUCo5WAwH7qruEcuQkmmvUsWEluAYyeU5jGM6DXt7H92EAibV/xSIVHWX8Yyz1Db4ROW23pX09GrBZEKhZFIPnHa1TaQeHx8NjpOV3xCnmCAe/b1hC1VmvmAd3Aa75x+8hb/dDRO1OGTK2tMlv8WJ+xDEcghp2acnq5lSkGeOoMmoQmAKJD24SKhqxVxJsFzuUZ1sA1Hfd6Elru2AhprS0L7ReW4R0Imkt0uLm6EpFXnyqB0yvcss7zmg7BXXOBPcXrENuM3FcJl+mB6oaXdXNL1CbJESuBdD10V4A6Ipc=
