version: '3'

services:

  app:
    build: .
    env_file:
      - .env
    environment:
      APP_VERSION: "^0.3.0"
      NODE_ENV: "referens"
      LDAP_URI : "ldaps://ldap.ug.kth.se"
      LDAP_USERNAME: "system-lms-integration@ug.kth.se"
    ports:
      - 3000
    labels:
      - se.kth.cluster=stage
      - se.kth.slackChannels="#team-e-larande-build"
