version: "2"

services:
  app:
    build: .
    env_file:
      - .env
    environment:
      LDAP_URI: "ldaps://ldap.ug.kth.se"
      LDAP_USERNAME: "system-lms-integration@ug.kth.se"
    ports:
      - 3000:3000
