# Run integration tests inside its own container
# Read more: https://github.com/kth/evolene#integration-testing
version: '3.2'

services:
  integration_tests:
    build: .
    image: $LOCAL_IMAGE_ID
    tty: true
    command: >
      sh -c "apk add openssl &&
             npm install &&
             npm test:integration"
    environment:
      - PROXY_PREFIX_PATH
      - CSV_DIR
      - LOG_LEVEL
      - LOG_SRC
      - CANVAS_API_URL
      - CANVAS_API_KEY
      - AZURE_SHARED_ACCESS_KEY_NAME
      - AZURE_SHARED_ACCESS_KEY
