# Run unit tests inside its own container
# Read more: https://github.com/kth/evolene#unit-testing
version: '3.2'

services:
  unit_test:
    build: .
    image: $LOCAL_IMAGE_ID
    tty: true
    command: >
      sh -c "apk add openssl &&
             npm install &&
             npm test"
