# Run unit tests inside its own container
# Read more: https://github.com/kth/evolene#unit-testing
version: '3.2'

services:
  unit_test:
    build: .
    image: $LOCAL_IMAGE_ID

    volumes:
      - ./test:/lms-sync-users/test
      - ./node_modules:/lms-sync-users/node_modules

    tty: true
    command: npm run test:docker-unit
